insert into Studies (id, Name) values (1, 'Marketing');
insert into Studies (id, Name) values (2, 'Human Resources');
insert into Studies (id, Name) values (3, 'Accounting');
insert into Studies (id, Name) values (4, 'Engineering');
insert into Studies (id, Name) values (5, 'Training');
insert into Studies (id, Name) values (6, 'Engineering');
insert into Studies (id, Name) values (7, 'Training');
insert into Studies (id, Name) values (8, 'Sales');
insert into Studies (id, Name) values (9, 'Human Resources');
insert into Studies (id, Name) values (10, 'Engineering');
insert into Studies (id, Name) values (11, 'Marketing');
insert into Studies (id, Name) values (12, 'Training');
insert into Studies (id, Name) values (13, 'Sales');
insert into Studies (id, Name) values (14, 'Training');
insert into Studies (id, Name) values (15, 'Accounting');
insert into Studies (id, Name) values (16, 'Research and Development');
insert into Studies (id, Name) values (17, 'Training');
insert into Studies (id, Name) values (18, 'Engineering');
insert into Studies (id, Name) values (19, 'Human Resources');
insert into Studies (id, Name) values (20, 'Product Management');
insert into Studies (id, Name) values (21, 'Business Development');
insert into Studies (id, Name) values (22, 'Support');
insert into Studies (id, Name) values (23, 'Accounting');
insert into Studies (id, Name) values (24, 'Human Resources');
insert into Studies (id, Name) values (25, 'Marketing');
insert into Studies (id, Name) values (26, 'Legal');
insert into Studies (id, Name) values (27, 'Engineering');
insert into Studies (id, Name) values (28, 'Business Development');
insert into Studies (id, Name) values (29, 'Engineering');
insert into Studies (id, Name) values (30, 'Marketing');
insert into Studies (id, Name) values (31, 'Research and Development');
insert into Studies (id, Name) values (32, 'Research and Development');
insert into Studies (id, Name) values (33, 'Accounting');
insert into Studies (id, Name) values (34, 'Marketing');
insert into Studies (id, Name) values (35, 'Support');
insert into Studies (id, Name) values (36, 'Marketing');
insert into Studies (id, Name) values (37, 'Human Resources');
insert into Studies (id, Name) values (38, 'Product Management');
insert into Studies (id, Name) values (39, 'Product Management');
insert into Studies (id, Name) values (40, 'Sales');
insert into Studies (id, Name) values (41, 'Engineering');
insert into Studies (id, Name) values (42, 'Business Development');
insert into Studies (id, Name) values (43, 'Support');
insert into Studies (id, Name) values (44, 'Training');
insert into Studies (id, Name) values (45, 'Engineering');
insert into Studies (id, Name) values (46, 'Research and Development');
insert into Studies (id, Name) values (47, 'Support');
insert into Studies (id, Name) values (48, 'Engineering');
insert into Studies (id, Name) values (49, 'Product Management');
insert into Studies (id, Name) values (50, 'Accounting');
insert into Studies (id, Name) values (51, 'Legal');
insert into Studies (id, Name) values (52, 'Services');
insert into Studies (id, Name) values (53, 'Legal');
insert into Studies (id, Name) values (54, 'Human Resources');
insert into Studies (id, Name) values (55, 'Human Resources');
insert into Studies (id, Name) values (56, 'Services');
insert into Studies (id, Name) values (57, 'Product Management');
insert into Studies (id, Name) values (58, 'Legal');
insert into Studies (id, Name) values (59, 'Training');
insert into Studies (id, Name) values (60, 'Product Management');
insert into Studies (id, Name) values (61, 'Training');
insert into Studies (id, Name) values (62, 'Services');
insert into Studies (id, Name) values (63, 'Product Management');
insert into Studies (id, Name) values (64, 'Engineering');
insert into Studies (id, Name) values (65, 'Human Resources');
insert into Studies (id, Name) values (66, 'Services');
insert into Studies (id, Name) values (67, 'Engineering');
insert into Studies (id, Name) values (68, 'Human Resources');
insert into Studies (id, Name) values (69, 'Accounting');
insert into Studies (id, Name) values (70, 'Sales');
insert into Studies (id, Name) values (71, 'Sales');
insert into Studies (id, Name) values (72, 'Services');
insert into Studies (id, Name) values (73, 'Services');
insert into Studies (id, Name) values (74, 'Business Development');
insert into Studies (id, Name) values (75, 'Services');
insert into Studies (id, Name) values (76, 'Accounting');
insert into Studies (id, Name) values (77, 'Accounting');
insert into Studies (id, Name) values (78, 'Legal');
insert into Studies (id, Name) values (79, 'Sales');
insert into Studies (id, Name) values (80, 'Research and Development');
insert into Studies (id, Name) values (81, 'Sales');
insert into Studies (id, Name) values (82, 'Research and Development');
insert into Studies (id, Name) values (83, 'Human Resources');
insert into Studies (id, Name) values (84, 'Marketing');
insert into Studies (id, Name) values (85, 'Accounting');
insert into Studies (id, Name) values (86, 'Legal');
insert into Studies (id, Name) values (87, 'Services');
insert into Studies (id, Name) values (88, 'Support');
insert into Studies (id, Name) values (89, 'Product Management');
insert into Studies (id, Name) values (90, 'Training');
insert into Studies (id, Name) values (91, 'Training');
insert into Studies (id, Name) values (92, 'Accounting');
insert into Studies (id, Name) values (93, 'Research and Development');
insert into Studies (id, Name) values (94, 'Training');
insert into Studies (id, Name) values (95, 'Services');
insert into Studies (id, Name) values (96, 'Business Development');
insert into Studies (id, Name) values (97, 'Marketing');
insert into Studies (id, Name) values (98, 'Engineering');
insert into Studies (id, Name) values (99, 'Product Management');
insert into Studies (id, Name) values (100, 'Business Development');
